spring:
  cloud:
    stream:
      bindings:
        output:
          destination: http-message
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092


server:
  port: 8090

http:
  prefix: 'Prefix'